### ISSUE TITLE
URL value does not resolve

### ISSUE THREAD

**Issue by SavannahDearing** [inferno-community/fhir-validator-app#45]
Testing with Json:
`
     {
	"entry" : 
	[
		{
			"fullUrl" : "https://www.medentmobiletest.com/fhir/R4/savcw235/Patient/MRN.5556.5e5adcf6-aa91-4dde-a5bb-67b2935bb18a",
			"resource" : 
			{
				"id" : "MRN.5556.5e5adcf6-aa91-4dde-a5bb-67b2935bb18a",
				"resourceType" : "Patient"
			},
			"search" : 
			{
				"mode" : "match"
			}
		}
	],
	"id" : "3946420210303T1452180Z",
	"link" : 
	[
		{
			"relation" : "self",
			"url" : "https://www.medentmobiletest.com/fhir/R4/savcw235/Patient?_id=MRN.5556.5e5adcf6-aa91-4dde-a5bb-67b2935bb18a"
		}
	],
	"meta" : 
	{
		"lastUpdated" : "2021-03-03T14:52:18.0Z"
	},
	"resourceType" : "Bundle",
	"total" : 1,
	"type" : "searchset"
}
`

Validator results:
1) Bundle.entry[0].fullUrl: URL value 'https://www.medentmobiletest.com/fhir/R4/savcw235/Patient/MRN.5556.5e5adcf6-aa91-4dde-a5bb-67b2935bb18a' does not resolve on line 6. Jump to error.
2) Bundle.link[0].url: URL value 'https://www.medentmobiletest.com/fhir/R4/savcw235/Patient?_id=MRN.5556.5e5adcf6-aa91-4dde-a5bb-67b2935bb18a' does not resolve on line 24. Jump to error.

Going to either URL directly will give an authentication error.  Trying to understand what the validator is looking for here, thanks!

**Comment by yunwwang** [comment]
This is an error message from HL7 Validator. The validator tries to verify that this URL is resolvable by fetching URL pointed resource. Since these urls require authentication, the validator could not read the resources directly. 
The URL validation is disabled in fhir-validator-service recently. (https://github.com/inferno-community/fhir-validator-wrapper/pull/30). This app will use the latest fhir-validator-service in the next release. At the same, you can ignore any "URL value xxx does not resolve" error.

**Comment by SavannahDearing** [comment]
Thanks for the information!
